arcs:

  - key: learning_hygiene
    description: learning hygiene

    arcs:
      basic_learning:
        min_tier: 0
        max_tier: 5
        goal: basic hygiene concepts such as learning to brush teeth, learning to wash hands, or learning to take a bath

      advanced_learning:
        min_tier: 6
        max_tier: 13
        goal: more complex hygiene concepts such as learning to maintain good personal hygiene, learning to use hygiene products effectively, or learning to follow proper hygiene practices

    shared_locations:
      - at home
      - at school
      - at grandparent's house
      - at a friend's house
      - at a community center
      - at a music store
      - at a band practice room

    shared_banned_tones:
      - imaginative
  - key: learning_music
    description: learning music

    arcs:
      basic_learning:
        min_tier: 0
        max_tier: 3
        goal: simple music concepts such as learning to sing a song, learning to play a simple instrument, or learning to dance to music

      advanced_learning:
        min_tier: 3
        max_tier: 13
        goal: more complex music concepts such as learning to read music, learning to play a more complex instrument, or learning to dance to more complex music

    shared_locations:
      - at home
      - at school
      - at grandparent's house
      - at a friend's house
      - at a community center
      - at a music store
      - at a band practice room

    shared_banned_tones:
      - imaginative

  - key: learning_sports
    description: learning sports

    arcs:
      basic_learning:
        min_tier: 0
        max_tier: 3
        goal: learning to play sports such as learning to throw and catch a ball, learning to kick a ball, or learning to swim

      advanced_learning:
        min_tier: 1
        max_tier: 6
        goal: learning to do more complex sports activities such as learning to play a team sport, learning to do a sport competitively, or learning to do a sport at a high level
    shared_locations:
      - at home
      - at school
      - at grandparent's house
      - at a friend's house
      - at a community center
      - at a sports field
      - at a gym
      - at a sports club
      - during a sports practice
    
    shared_banned_tones:
      - imaginative


  - key: learning_to_code
    description: learning to code

    arcs:
      basic_learning:
        min_tier: 10
        max_tier: 13
        goal: basic coding concepts such as learning to write simple programs, learning to use basic programming syntax, or learning to debug simple code
      advanced_learning:
        min_tier: 10
        max_tier: 13
        goal: more complex coding concepts such as learning to write more complex programs, learning to use more advanced programming syntax, or learning to debug more complex code

    shared_locations:
      - at home
      - at school
      - at grandparent's house
      - at a friend's house
      - at a community center
      - at a coding bootcamp
      

    shared_banned_tones:
      - imaginative
    
  - key: learning_cooking
    description: learning to cook

    arcs:
      basic_learning:
        min_tier: 4
        max_tier: 8
        goal: basic cooking skills such as learning to follow a simple recipe, learning to use basic kitchen tools, or learning to cook simple meals
      advanced_learning:
        min_tier: 6
        max_tier: 13
        goal: more complex cooking skills such as learning to create more complex recipes, learning to use more advanced kitchen tools, or learning to cook more complex meals

    shared_locations:
      - at home
      - at school
      - at grandparent's house
      - at a friend's house
      - at a community center
      - at a cooking class

    shared_banned_tones:
      - imaginative

  - key: learning_religious_or_cultural_practices
    description: learning religious or cultural practices

    arcs:
      basic_learning:
        min_tier: 0
        max_tier: 3
        goal: basic religious or cultural practices such as learning to say a prayer, learning to do a cultural dance, or learning to celebrate a religious holiday
      advanced_learning:
        min_tier: 2
        max_tier: 13
        goal: more complex religious or cultural practices such as learning to do a religious ceremony, learning to do a cultural ritual, or learning to celebrate a religious or cultural holiday

    shared_locations:
      - at home
      - at school
      - at grandparent's house
      - at a friend's house
      - at a community center
      - at a religious or cultural center
      - during a religious or cultural ceremony

    shared_banned_tones:
      - imaginative

  - key: learning_art
    description: learning art

    arcs:
      basic_learning:
        min_tier: 0
        max_tier: 3
        goal: basic art concepts such as learning to draw simple shapes, learning to use basic art materials, or learning to create simple art projects
      advanced_learning:
        min_tier: 1
        max_tier: 13
        goal: more complex art concepts such as learning to draw more complex shapes, learning to use more advanced art materials, or learning to create more complex art projects

    shared_locations:
      - at home
      - at school
      - at grandparent's house
      - at a friend's house
      - at a community center
      - at an art class

  - key: learning_physics
    description: learning physics

    arcs:
      basic_learning:
        min_tier: 4
        max_tier: 9
        goal: basic physics concepts such as learning about gravity, learning about motion, or learning about energy
      advanced_learning:
        min_tier: 10
        max_tier: 13
        goal: more complex physics concepts such as learning about quantum mechanics, learning about relativity, or learning about astrophysics

    shared_locations:
      - at home
      - at school
      - at a friend's house
      - at a science museum

    shared_banned_tones:
      - imaginative

  - key: learning_chemistry
    description: learning chemistry

    arcs:
      basic_learning:
        min_tier: 4
        max_tier: 9
        goal: basic chemistry concepts such as learning about atoms, learning about molecules, or learning about chemical reactions
      advanced_learning:
        min_tier: 10
        max_tier: 13
        goal: more complex chemistry concepts such as learning about organic chemistry, learning about biochemistry, or learning about physical chemistry

    shared_locations:
      - at home
      - at school
      - at a friend's house
      - at a science museum

    shared_banned_tones:
      - imaginative
    

  - key: learning_biology
    description: learning biology

    arcs:
      basic_learning:
        min_tier: 4
        max_tier: 9
        goal: basic biology concepts such as learning about cells, learning about organisms, or learning about ecosystems
      advanced_learning:
        min_tier: 10
        max_tier: 13
        goal: more complex biology concepts such as learning about genetics, learning about evolution, or learning about ecology

    shared_locations:
      - at home
      - at school
      - at a friend's house
      - at a science museum

    shared_banned_tones:
      - imaginative

  - key: learning_history
    description: learning history

    arcs:
      basic_learning:
        min_tier: 3
        max_tier: 6
        goal: basic history concepts such as learning about historical events, learning about historical figures, or learning about historical time periods
      advanced_learning:
        min_tier: 7
        max_tier: 13
        goal: more complex history concepts such as learning about historical causes and effects, learning about historical interpretations, or learning about historical debates

    shared_locations:
      - at home
      - at school
      - at a friend's house
      - at a museum

    shared_banned_tones:
      - imaginative
